### ISSUE TITLE
Sockets.route should preserve handler docstrings/annotations/etc.

### ISSUE THREAD

**Issue by achimnol** [heroku-python/flask-sockets#50]
The original Flask framework [uses `functools.update_wrapper()`](https://github.com/pallets/flask/blob/45c8fb3f3fea9cc2599438e751906f509e19f0e2/flask/app.py#L67) for handler registration methods such as [add_url_rule()](https://github.com/pallets/flask/blob/45c8fb3f3fea9cc2599438e751906f509e19f0e2/flask/app.py#L1083-L1084) so that docstrings, annotations, and other metadata of the `app.route()`-wrapped function becomes equivalent to those of the original user-defined handler function.
To be consistent, `Sockets.route()` or `Sockets.add_url_rule()` method should do this as well.

**Comment by tkrajca** [comment]
Cool, @achimnol have you got a pull request?

**Comment by achimnol** [comment]
Ooops, I pointed the wrong stuff.
`Sockets.route()` is working as expected, since the decorator just returns `f` as-is and only calls `add_url_rule()` as a side-effect.
The root cause of my problem was a missing entry in `__all__`.
Sorry for bothering. 😞 (We should not write codes when sleepy..... 😪)
