### ISSUE TITLE
Deploying behind uwsgi?

### ISSUE THREAD

**Issue by trbabb** [heroku-python/flask-sockets#54]
I'm seeing issues when attempting to deploy behind nginx/uwsgi. (Apologies if this is turns out to not be a flask-sockets issue).

Specifically, the `'wsgi.websockets'` key is missing from the request environment and so flask-sockets just routes to the normal app and the websocket request 404s. (I've set `gevent = 100` in the uwsgi config to no avail).

Happy to provide configs if need be, or receive pointers on how to set up the nginx/uwsgi configs so that websocket requests to `flask-sockets` will complete. 

thanks for your help!

**Comment by kennethreitz** [comment]
This library only supports gunicorn.
