### ISSUE TITLE
Documentation on sending binary data?

### ISSUE THREAD

**Issue by d33tah** [heroku-python/flask-sockets#66]
I'd like to send binary data using this library, but I have no idea how to get there. So far I'm only getting encoding errors - probably because it's assumed that I'm sending ASCII strings. How to get around that?

**Comment by colin-riddell** [comment]
You _may_ be able to provide `socket.send()` the argument ` Binary=True`.
Eg:
```
socket.send(payload,  Binary=True)
```

**Comment by colin-riddell** [comment]
Yes! Seems like you can. Ref: https://github.com/jgelens/gevent-websocket/blob/93d6b72a49742cfd615cc102a4c628acf2568465/geventwebsocket/websocket.py#L339

flask-sockets uses gevent-websocket interface thus uses their `.send`

**Comment by d33tah** [comment]
Awesome, thanks!
